server:
  port: 8081

spring:
  application:
    name: car-rental-service

  datasource:
    url: jdbc:mysql://localhost:3306/seng400
    username: root
    password: mysql123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true